// eslint-disable-next-line import/no-extraneous-dependencies
import { faker } from '@faker-js/faker';

export default [
  {
    id: faker.string.uuid(),
    name: faker.lorem.words({ min: 1, max: 3 }),
    height: `${faker.number.int({ min: 400, max: 700 })}m npm`,
    description: faker.lorem.words({ min: 10, max: 50 }),
    trial: faker.lorem.words({ min: 2, max: 5 }),
    localizationLat: faker.location.latitude(),
    LocalizationLng: faker.location.longitude(),
    image: faker.image.urlLoremFlickr({ category: 'mountains' }),
  },
  {
    id: faker.string.uuid(),
    name: faker.lorem.words({ min: 1, max: 3 }),
    height: `${faker.number.int({ min: 400, max: 700 })}m npm`,
    description: faker.lorem.words({ min: 10, max: 50 }),
    trial: faker.lorem.words({ min: 2, max: 5 }),
    localizationLat: faker.location.latitude(),
    LocalizationLng: faker.location.longitude(),
    image: faker.image.urlLoremFlickr({ category: 'mountains' }),
  },
  {
    id: faker.string.uuid(),
    name: faker.lorem.words({ min: 1, max: 3 }),
    height: `${faker.number.int({ min: 400, max: 700 })}m npm`,
    description: faker.lorem.words({ min: 10, max: 50 }),
    trial: faker.lorem.words({ min: 2, max: 5 }),
    localizationLat: faker.location.latitude(),
    LocalizationLng: faker.location.longitude(),
    image: faker.image.urlLoremFlickr({ category: 'mountains' }),
  },
  {
    id: faker.string.uuid(),
    name: faker.lorem.words({ min: 1, max: 3 }),
    height: `${faker.number.int({ min: 400, max: 700 })}m npm`,
    description: faker.lorem.words({ min: 10, max: 50 }),
    trial: faker.lorem.words({ min: 2, max: 5 }),
    localizationLat: faker.location.latitude(),
    LocalizationLng: faker.location.longitude(),
    image: faker.image.urlLoremFlickr({ category: 'mountains' }),
  },
  {
    id: faker.string.uuid(),
    name: faker.lorem.words({ min: 1, max: 3 }),
    height: `${faker.number.int({ min: 400, max: 700 })}m npm`,
    description: faker.lorem.words({ min: 10, max: 50 }),
    trial: faker.lorem.words({ min: 2, max: 5 }),
    localizationLat: faker.location.latitude(),
    LocalizationLng: faker.location.longitude(),
    image: faker.image.urlLoremFlickr({ category: 'mountains' }),
  },
  {
    id: faker.string.uuid(),
    name: faker.lorem.words({ min: 1, max: 3 }),
    height: `${faker.number.int({ min: 400, max: 700 })}m npm`,
    description: faker.lorem.words({ min: 10, max: 50 }),
    trial: faker.lorem.words({ min: 2, max: 5 }),
    localizationLat: faker.location.latitude(),
    LocalizationLng: faker.location.longitude(),
    image: faker.image.urlLoremFlickr({ category: 'mountains' }),
  },
  {
    id: faker.string.uuid(),
    name: faker.lorem.words({ min: 1, max: 3 }),
    height: `${faker.number.int({ min: 400, max: 700 })}m npm`,
    description: faker.lorem.words({ min: 10, max: 50 }),
    trial: faker.lorem.words({ min: 2, max: 5 }),
    localizationLat: faker.location.latitude(),
    LocalizationLng: faker.location.longitude(),
    image: faker.image.urlLoremFlickr({ category: 'mountains' }),
  },
  {
    id: faker.string.uuid(),
    name: faker.lorem.words({ min: 1, max: 3 }),
    height: `${faker.number.int({ min: 400, max: 700 })}m npm`,
    description: faker.lorem.words({ min: 10, max: 50 }),
    trial: faker.lorem.words({ min: 2, max: 5 }),
    localizationLat: faker.location.latitude(),
    LocalizationLng: faker.location.longitude(),
    image: faker.image.urlLoremFlickr({ category: 'mountains' }),
  },
  {
    id: faker.string.uuid(),
    name: faker.lorem.words({ min: 1, max: 3 }),
    height: `${faker.number.int({ min: 400, max: 700 })}m npm`,
    description: faker.lorem.words({ min: 10, max: 50 }),
    trial: faker.lorem.words({ min: 2, max: 5 }),
    localizationLat: faker.location.latitude(),
    LocalizationLng: faker.location.longitude(),
    image: faker.image.urlLoremFlickr({ category: 'mountains' }),
  },
  {
    id: faker.string.uuid(),
    name: faker.lorem.words({ min: 1, max: 3 }),
    height: `${faker.number.int({ min: 400, max: 700 })}m npm`,
    description: faker.lorem.words({ min: 10, max: 50 }),
    trial: faker.lorem.words({ min: 2, max: 5 }),
    localizationLat: faker.location.latitude(),
    LocalizationLng: faker.location.longitude(),
    image: faker.image.urlLoremFlickr({ category: 'mountains' }),
  },
  {
    id: faker.string.uuid(),
    name: faker.lorem.words({ min: 1, max: 3 }),
    height: `${faker.number.int({ min: 400, max: 700 })}m npm`,
    description: faker.lorem.words({ min: 10, max: 50 }),
    trial: faker.lorem.words({ min: 2, max: 5 }),
    localizationLat: faker.location.latitude(),
    LocalizationLng: faker.location.longitude(),
    image: faker.image.urlLoremFlickr({ category: 'mountains' }),
  },
  {
    id: faker.string.uuid(),
    name: faker.lorem.words({ min: 1, max: 3 }),
    height: `${faker.number.int({ min: 400, max: 700 })}m npm`,
    description: faker.lorem.words({ min: 10, max: 50 }),
    trial: faker.lorem.words({ min: 2, max: 5 }),
    localizationLat: faker.location.latitude(),
    LocalizationLng: faker.location.longitude(),
    image: faker.image.urlLoremFlickr({ category: 'mountains' }),
  },
  {
    id: faker.string.uuid(),
    name: faker.lorem.words({ min: 1, max: 3 }),
    height: `${faker.number.int({ min: 400, max: 700 })}m npm`,
    description: faker.lorem.words({ min: 10, max: 50 }),
    trial: faker.lorem.words({ min: 2, max: 5 }),
    localizationLat: faker.location.latitude(),
    LocalizationLng: faker.location.longitude(),
    image: faker.image.urlLoremFlickr({ category: 'mountains' }),
  },
  {
    id: faker.string.uuid(),
    name: faker.lorem.words({ min: 1, max: 3 }),
    height: `${faker.number.int({ min: 400, max: 700 })}m npm`,
    description: faker.lorem.words({ min: 10, max: 50 }),
    trial: faker.lorem.words({ min: 2, max: 5 }),
    localizationLat: faker.location.latitude(),
    LocalizationLng: faker.location.longitude(),
    image: faker.image.urlLoremFlickr({ category: 'mountains' }),
  },
];
