// eslint-disable-next-line import/no-extraneous-dependencies
import { faker } from '@faker-js/faker';
import users from '@/lib/mockData/users';
import peaks from '@/lib/mockData/peaks';

export default [
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
  {
    id: faker.string.uuid(),
    author: users[faker.number.int({ min: 0, max: users.length - 1 })],
    createdAt: faker.date.past(),
    notes: faker.lorem.paragraph(),
    photo: faker.image.urlLoremFlickr({ category: 'mountains' }),
    peak: peaks[faker.number.int({ min: 0, max: peaks.length - 1 })],
  },
];
